# POST http://localhost:5000/api/enrollments
# Content-Type: application/json

# {
#   "studentId": "1234",
#   "courseCode": "CS101"
# }
//GET  http://localhost:5000/api/enrollments
//http://localhost:5000/api/test/nplusone
//http://localhost:5000/api/test/nplusone-fixed
